import { IAppointment, IAppointmentSymptoms } from '@/types/appointment.interface';
import { AppointmentStatus } from '@/types/appointmentStatus.enum';
import { IHospital } from '@/types/hospital.interface';
import { IPatient } from '@/types/patient.interface';
import { IDoctor } from '@/types/doctor.interface';
import { AppointmentType, SlotStatus } from '@/types/slots.interface';
import type { PaginationData } from '@/components/ui/table';
import type { IPatientSymptomMap } from '@/types/consultation.interface';

export const ENABLE_DUMMY_APPOINTMENTS = process.env.NODE_ENV !== 'production';

const emptySymptomsMap: IPatientSymptomMap = {
  neurological: [],
  cardiovascular: [],
  gastrointestinal: [],
  musculoskeletal: [],
  genitourinary: [],
  integumentary: [],
  endocrine: [],
};

const makeSymptoms = (appointmentId: string): IAppointmentSymptoms => ({
  id: `sym-${appointmentId}`,
  createdAt: new Date().toISOString(),
  appointmentId,
  complaints: [],
  medicinesTaken: [],
  symptoms: emptySymptomsMap,
});

const makePatient = (firstName: string, lastName: string): IPatient =>
  ({
    id: `pat-${firstName.toLowerCase()}`,
    firstName,
    lastName,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,
    status: 'accepted',
    contact: '+233 24 000 0000',
    profilePicture: '',
    gender: 'other',
    dob: '1995-01-01',
    orgId: 'demo-org',
    createdAt: new Date(),
    updatedAt: new Date(),
    lifestyle: {},
    insuranceInfo: 'NHIS',
  }) as unknown as IPatient;

const makeDoctor = (firstName: string, lastName: string, specialization: string): IDoctor =>
  ({
    id: `doc-${firstName.toLowerCase()}`,
    firstName,
    lastName,
    email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`,
    status: 'accepted',
    contact: '+233 20 000 0000',
    profilePicture: '',
    gender: 'other',
    dob: '1988-01-01',
    orgId: 'demo-org',
    createdAt: new Date(),
    updatedAt: new Date(),
    MDCRegistration: 'MDC-000000',
    address: 'Liberation Road, Accra',
    city: 'Accra',
    appointmentSlots: [],
    qualifications: ['MBChB'],
    specializations: [specialization],
    schoolsAttended: ['University of Ghana'],
    experience: 7,
    notifications: {
      email: true,
      appointments: true,
      messages: true,
      fileRecordRequest: true,
    },
    bio: 'Experienced clinician focused on patient-centered care.',
    languages: ['English'],
    awards: [],
    IDs: { front: '', back: '' },
    rate: 4.6,
    balance: 0,
    signaturePath: '',
    ratings: 4.6,
    hasDefaultPayment: true,
    hasSlot: true,
  }) as unknown as IDoctor;

const demoHospital: IHospital = {
  id: 'demo-hospital',
  name: 'Zomujo General Hospital',
  email: 'admin@hospital.com',
  location: 'Liberation Road, Accra',
  status: 'approved',
  distance: 0,
  gpsLink: 'https://maps.google.com/?q=Liberation+Road+Accra',
  image: null,
  supportedInsurance: ['NHIS'],
  specialties: ['General Practice', 'Cardiology'],
  regularFee: 120,
  createdAt: new Date(),
  updatedAt: new Date(),
} as unknown as IHospital;

const isoDate = (daysFromToday: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromToday);
  return d.toISOString().slice(0, 10);
};

export const DUMMY_HOSPITAL_APPOINTMENTS: IAppointment[] = [
  {
    id: 'appt-001',
    createdAt: new Date().toISOString(),
    patient: makePatient('Ama', 'Mensah'),
    doctor: makeDoctor('Kofi', 'Owusu', 'General Practice'),
    org: demoHospital,
    type: AppointmentType.Visit,
    startTime: '09:00:00',
    endTime: '09:45:00',
    slot: {
      id: 'slot-001',
      date: isoDate(0),
      startTime: '09:00:00',
      endTime: '09:45:00',
      type: AppointmentType.Visit,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-kofi',
      patternId: 'pattern-001',
      exceptionId: null,
    },
    status: AppointmentStatus.Pending,
    reason: 'Fever and headache',
    additionalInfo: 'Patient reports symptoms started 2 days ago.',
    symptoms: makeSymptoms('appt-001'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-002',
    createdAt: new Date().toISOString(),
    patient: makePatient('Yaw', 'Boateng'),
    doctor: makeDoctor('Esi', 'Addo', 'Cardiology'),
    org: demoHospital,
    type: AppointmentType.Virtual,
    startTime: '11:00:00',
    endTime: '11:45:00',
    slot: {
      id: 'slot-002',
      date: isoDate(1),
      startTime: '11:00:00',
      endTime: '11:45:00',
      type: AppointmentType.Virtual,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-esi',
      patternId: 'pattern-002',
      exceptionId: null,
    },
    status: AppointmentStatus.Accepted,
    reason: 'Chest discomfort',
    additionalInfo: 'Follow-up from last month’s consultation.',
    symptoms: makeSymptoms('appt-002'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-003',
    createdAt: new Date().toISOString(),
    patient: makePatient('Nana', 'Asare'),
    doctor: makeDoctor('Kofi', 'Owusu', 'General Practice'),
    org: demoHospital,
    type: AppointmentType.Visit,
    startTime: '14:00:00',
    endTime: '14:45:00',
    slot: {
      id: 'slot-003',
      date: isoDate(2),
      startTime: '14:00:00',
      endTime: '14:45:00',
      type: AppointmentType.Visit,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-kofi',
      patternId: 'pattern-003',
      exceptionId: null,
    },
    status: AppointmentStatus.Completed,
    reason: 'Routine checkup',
    additionalInfo: 'Vitals normal; no complaints.',
    symptoms: makeSymptoms('appt-003'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-004',
    createdAt: new Date().toISOString(),
    patient: makePatient('Akosua', 'Bediako'),
    doctor: makeDoctor('Esi', 'Addo', 'Cardiology'),
    org: demoHospital,
    type: AppointmentType.Virtual,
    startTime: '08:00:00',
    endTime: '08:45:00',
    slot: {
      id: 'slot-004',
      date: isoDate(3),
      startTime: '08:00:00',
      endTime: '08:45:00',
      type: AppointmentType.Virtual,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-esi',
      patternId: 'pattern-004',
      exceptionId: null,
    },
    status: AppointmentStatus.Progress,
    reason: 'Blood pressure review',
    additionalInfo: 'Patient currently on medication; needs dosage review.',
    symptoms: makeSymptoms('appt-004'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-005',
    createdAt: new Date().toISOString(),
    patient: makePatient('Kojo', 'Antwi'),
    doctor: makeDoctor('Kofi', 'Owusu', 'General Practice'),
    org: demoHospital,
    type: AppointmentType.Visit,
    startTime: '10:30:00',
    endTime: '11:15:00',
    slot: {
      id: 'slot-005',
      date: isoDate(4),
      startTime: '10:30:00',
      endTime: '11:15:00',
      type: AppointmentType.Visit,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-kofi',
      patternId: 'pattern-005',
      exceptionId: null,
    },
    status: AppointmentStatus.Accepted,
    reason: 'Stomach discomfort',
    additionalInfo: 'Pain after meals, no vomiting.',
    symptoms: makeSymptoms('appt-005'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-006',
    createdAt: new Date().toISOString(),
    patient: makePatient('Abena', 'Sarfo'),
    doctor: makeDoctor('Esi', 'Addo', 'Cardiology'),
    org: demoHospital,
    type: AppointmentType.Visit,
    startTime: '13:00:00',
    endTime: '13:45:00',
    slot: {
      id: 'slot-006',
      date: isoDate(5),
      startTime: '13:00:00',
      endTime: '13:45:00',
      type: AppointmentType.Visit,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-esi',
      patternId: 'pattern-006',
      exceptionId: null,
    },
    status: AppointmentStatus.Cancelled,
    reason: 'Follow-up consultation',
    additionalInfo: 'Cancelled by patient due to travel.',
    symptoms: makeSymptoms('appt-006'),
    lab: [],
    diagnosis: [],
  },
  {
    id: 'appt-007',
    createdAt: new Date().toISOString(),
    patient: makePatient('Kwame', 'Dapaah'),
    doctor: makeDoctor('Kofi', 'Owusu', 'General Practice'),
    org: demoHospital,
    type: AppointmentType.Virtual,
    startTime: '16:00:00',
    endTime: '16:45:00',
    slot: {
      id: 'slot-007',
      date: isoDate(6),
      startTime: '16:00:00',
      endTime: '16:45:00',
      type: AppointmentType.Virtual,
      status: SlotStatus.Available,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      doctorId: 'doc-kofi',
      patternId: 'pattern-007',
      exceptionId: null,
    },
    status: AppointmentStatus.Declined,
    reason: 'Skin rash',
    additionalInfo: 'Declined due to insufficient booking details.',
    symptoms: makeSymptoms('appt-007'),
    lab: [],
    diagnosis: [],
  },
];

export const DUMMY_HOSPITAL_APPOINTMENTS_PAGINATION: PaginationData = {
  total: DUMMY_HOSPITAL_APPOINTMENTS.length,
  pageSize: 10,
  page: 1,
  nextPage: null,
  prevPage: null,
  totalPages: 1,
};
